version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "23:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
